### ISSUE TITLE
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="ytp-play-button ytp-button"> is not clickable at point (59,481) because another element <tp-yt-iron-overlay-backdrop class="opened"> obscures it

### ISSUE THREAD

**Issue by molnaredom** [CYBERDEVILZ/YoutubeBot#41]
```/home/molnar/YoutubeBot2/venv/bin/python /home/molnar/YoutubeBot2/Firefox/YouTubeBot.py
resolution = 2240.0, 1260.0
img0 size -> 1045, 588
img1 size -> 583, 121
thumbnail size -> 1045, 588
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/molnar/YoutubeBot2/Firefox/YouTubeBot.py", line 89, in start
    plybtn.click()
  File "/home/molnar/YoutubeBot2/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/molnar/YoutubeBot2/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/molnar/YoutubeBot2/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/molnar/YoutubeBot2/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="ytp-play-button ytp-button"> is not clickable at point (59,481) because another element <tp-yt-iron-overlay-backdrop class="opened"> obscures it
```
`https://www.youtube.com/watch?v=AJEg-d-U2eY`

![image](https://user-images.githubusercontent.com/77636185/214356244-21847e01-4bef-470b-bb2e-12ef4e552727.png)
![image](https://user-images.githubusercontent.com/77636185/214356806-28480127-0a6e-42ee-8deb-08f866becf06.png)

**Comment by molnaredom** [comment]
Maybe the program does not click on the ACCEPT ALL button?

**Comment by AyaanAhmed25** [comment]
Im facing the same issue

**Comment by johndeve26** [comment]
i can help you to fix the bot to click reject all. then it works perfectly
